[workspace]
members = ["bevy-reflect-deser", "template-kdl", "multierr-span"]
resolver = "2"


[patch.crates-io]
bevy_reflect = { git = "https://github.com/bevyengine/bevy.git", branch="main"}
bevy_utils = { git = "https://github.com/bevyengine/bevy.git", branch="main"}
