[workspace]
members = ["bevy-reflect-deser", "template-kdl"]
resolver = "2"


[patch.crates-io]
bevy_reflect = { git = "https://github.com/MrGVSV/bevy.git", branch="reflect-type-info"}
bevy_utils = { git = "https://github.com/MrGVSV/bevy.git", branch="reflect-type-info"}
